### ISSUE TITLE
Semantics of "content"

### ISSUE THREAD

**Issue by staticmade** [thewarholmuseum/digital-strategy#1]
Should we institutionally be referring to museum-created media and collection objects as something other than _content_? We should be more specific in describing our subject matter...i.e. artwork, scholarship, multimedia, metadata, design elements, user interfaces, etc.

**Comment by sebchan** [comment]
In your case, i think 'artworks and their stories' might be a good alternative. "Smooshing" it all together into a catch-all term doesn't do any of them justice, and when other industries use the term 'content' it means something interchangeable and of short-term value. I don't think museums want to get caught up in that.

**Comment by staticmade** [comment]
With the most recent push on 4/1/15, we've eliminated using the word 'content' in favor of more meaningful language.
